#!/bin/sh

# there brief explanations what each environemt variable does here, but
# please consult the telive manual: telive_doc.pdf
# sq5bpf

ulimit -c unlimited
export PATH=$PATH:/tetra/bin

# TETRA_OUTDIR - directory where to write the recorded ACELP voice files
# if unset defaults to /tetra/in
export TETRA_OUTDIR=/tetra/in

# TETRA_LOGFILE - filename where to write the log.
# if unset defaults to telive.log
export TETRA_LOGFILE=/tetra/log/telive.log

# TETRA_PORT - udp port where telive listens for communication from tetra-rx
# if unset defaults to 7379
export TETRA_PORT=7379

# TETRA_KEYS - if set, then telive behaves as if there keys are pressed at start
# if unset, nothing is done
#export TETRA_KEYS=lR #example: enable logging and recording
export TETRA_KEYS=m #enable mutessi

# TETRA_SSI_FILTER - a extended wildcard expression that determines which SSIs 
# are selected for playing live (if the filter is enabled)
# if unset, then no filter is used
#export TETRA_SSI_FILTER=1000 #example: match 1000
#export TETRA_SSI_FILTER=10?? #example: match 1000-1099
#export TETRA_SSI_FILTER='+(1000|[234]0??|?????)' #example: match 1000, 2000-2099, 3000-3099, 4000-4099, and any 5 digit number, you still have to enable the filter with f
# BIG FAT WARNING: if you're using a system without extended wildcard expressions  (like OSX), then you are left with standard wildcard expansion, the +(xxxx) will not work

# TETRA_KML_FILE - if set, the locations will be written periodically to this 
# file in KML format
export TETRA_KML_FILE=/tetra/log/tetra1.kml

# TETRA_KML_INTERVAL - this will set the maximum KML file refresh rate
# if unset, this will default to 30 seconds
export TETRA_KML_INTERVAL=3

# TETRA_SSI_DESCRIPTIONS - a file contaning textual descriptions of ssis
# if unset then no file is used
#export TETRA_SSI_DESCRIPTIONS=/tetra/ssi_descriptions

# internal tuning parameters, use at your own risk, the values shown are 
# defaults (all values are in seconds). if in doubt, RTFS
# if you don't know what you're doing, then don't touch these settings

# TETRA_REC_TIMEOUT - after how long we stop to record a usage identifier 
#export TETRA_REC_TIMEOUT=30

# TETRA_SSI_TIMEOUT - after how long we forget SSIs
#export TETRA_SSI_TIMEOUT=60

# TETRA_IDX_TIMEOUT -  after how long we disable the active flag
#export TETRA_IDX_TIMEOUT=8

# TETRA_CURPLAYING_TIMEOUT - after how long we stop playing the current 
# usage identifier
#export TETRA_CURPLAYING_TIMEOUT=5

# TETRA_FREQ_TIMEOUT - after how long we forget frequency info
# if unset, this will default to 600 seconds
#export TETRA_FREQ_TIMEOUT=600

# TETRA_LOCK_FILE - lock file to use between multiple instances 
# of telive, so that they don't all play at the same time 
#export TETRA_LOCK_FILE=/tetra/telive_lock

./telive

