#!/bin/sh

# there brief explanations what each environemt variable does here, but
# please consult the telive manual: telive_doc.pdf
# sq5bpf

ulimit -c unlimited
export PATH=$PATH:/tetra/bin

# TETRA_OUTDIR - directory where to write the recorded ACELP voice files
# if unset defaults to /tetra/in
export TETRA_OUTDIR=/tetra/in

# TETRA_LOGFILE - filename where to write the log.
# if unset defaults to telive.log
export TETRA_LOGFILE=/tetra/log/telive.log

# TETRA_PORT - udp port where telive listens for communication from tetra-rx
# if unset defaults to 7379
export TETRA_PORT=7379

# TETRA_KEYS - if set, then telive behaves as if there keys are pressed at start
# if unset, nothing is done
#export TETRA_KEYS=lR #example: enable logging and recording

# TETRA_SSI_FILTER - a extended wildcard expression that determines which SSIs 
# are selected for playing live (if the filter is enabled)
# if unset, then no filter is used
#export TETRA_SSI_FILTER=1000 #example: match 1000
#export TETRA_SSI_FILTER=10?? #example: match 1000-1099
#export TETRA_SSI_FILTER='+(1000|[234]0??|?????)' #example: match 1000, 2000-2099, 3000-3099, 4000-4099, and any 5 digit number, you still have to enable the filter with f

# uncomment the export TETRA_KML_FILE and export TETRA_KML_INTERVAL lines if you want KML handling
# these are commented out due to crashes that i have trouble debugging

# TETRA_KML_FILE - if set, the locations will be written periodically to this 
# file in KML format
#export TETRA_KML_FILE=/tetra/log/tetra1.kml

# TETRA_KML_INTERVAL - this will set the maximum KML file refresh rate
# if unset, this will default to 30 seconds
#export TETRA_KML_INTERVAL=3

# TETRA_SSI_DESCRIPTIONS - a file contaning textual descriptions of ssis
# if unset then no file is used
#export TETRA_SSI_DESCRIPTIONS=/tetra/ssi_descriptions

./telive

